### ISSUE TITLE
Upgrade yamllint to latest version

### ISSUE THREAD

**Issue by keimlink** [keimlink/docker-sphinx-doc#2]

**Comment by rarkins** [comment]
@keimlink would you consider [Renovate](https://github.com/apps/renovate) for this purpose? It comes with native lockfile support so no need to set anything up on CircleCI.

**Comment by keimlink** [comment]
@rarkins Thanks for bringing Renovate to my attention again. I discovered it several months ago as a Greenkeeper alternative. Didn't know it supports now also Dockerfiles. 😃

Currently there are some problems with Greenkeeper and CircleCI 2.0. Renovate uses a different approach that does not have these problems. That's very good!

I also love the automerge feature. It saves a lot of time.

Unfortunately the topic of this issue can't be solved by Renovate, because the yamllint Docker image is not being updated any longer. So I'll have to create my own Docker image to solve this. 😉

**Comment by keimlink** [comment]
Whoa, time to create a Docker image for this…
